name: CD

on:
  push:
    branches:
      - master

jobs:
  checking-deployable:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.checking-deployable-extension.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Check deployable an extension
      id: checking-deployable-extension
      run: |
        package_version=v$(node -e "console.log(require('./package.json').version)")
        new_tag=$(if [ ! $(git tag | grep $package_version) ]; then echo $package_version; fi)
        echo ::set-output name=new_tag::$new_tag

  creating-release_note:
    runs-on: ubuntu-latest
    needs: checking-deployable
    if: ${{ needs.checking-deployable.outputs.new_tag }}
    outputs:
      upload_url: ${{ steps.release-drafter.outputs.upload_url }}
    steps:
    - uses: release-drafter/release-drafter@v5
      id: release-drafter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ needs.checking-deployable.outputs.new_tag }}
        tag: ${{ needs.checking-deployable.outputs.new_tag }}
        publish: true

  deploying-extension:
    runs-on: ubuntu-latest
    needs: creating-release_note
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn build
    - run: yarn run pack
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.creating-release_note.outputs.upload_url }}
        asset_path: ./note-to-dropbox-paper.zip
        asset_name: note-to-dropbox-paper.zip
        asset_content_type: application/zip
